[package]
name = "wasmedge-wasinn-example-mobilenet"
version = "0.19.0"
authors = ["Second-State"]
readme = "README.md"
edition = "2018"
publish = false

[dependencies]
wasi-nn = { version = "0.2.1" }
